---
- name: Get existing server UUID
  shell: cat {{ rundeck_config_dir }}/framework.properties | grep rundeck.server.uuid | awk -F '=' '{print $2}'
  register: _rundeck_get_uuid
  changed_when: false

- name: Store UUID
  set_fact:
    # Used by _rundeck_framework
    _rundeck_uuid: "{{ _rundeck_get_uuid.stdout_lines[0] }}"

- name: Configure Rundeck framework
  template:
    src: properties.j2
    dest: "{{ rundeck_config_dir }}/framework.properties"
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_group }}"
    mode: u=rw,g=,o=
  vars:
    properties: "{{ _rundeck_framework }}"
  notify: restart rundeck

- name: Configure base Rundeck settings
  template:
    src: properties.j2
    dest: "{{ rundeck_config_dir }}/rundeck-config.properties"
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_group }}"
    mode: u=rw,g=,o=
  vars:
    properties: "{{ _rundeck_config | combine(rundeck_extra_config, recursive=True) }}"
  notify: restart rundeck

- name: Set session timeout
  xml:
    path: "{{ rundeck_base_dir }}/exp/webapp/WEB-INF/web.xml"
    xpath: /w:web-app/w:session-config/w:session-timeout
    value: "{{ rundeck_session_timeout|string }}"
    namespaces:
      w: http://java.sun.com/xml/ns/javaee
  when: rundeck_set_session_timeout
  notify: restart rundeck

- name: Configure Rundeck service
  template:
    src: rundeckd_defaults.j2
    dest: /etc/default/rundeckd
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: restart rundeck

- name: Create CLI user
  user:
    name: "{{ rundeck_cli_user }}"
    state: present
  register: _rundeck_cli_user

- name: Create ~/.rd directory for CLI user
  file:
    path: "{{ _rundeck_cli_user.home }}/.rd/"
    state: directory
    owner: "{{ rundeck_cli_user }}"
    group: "{{ rundeck_cli_user }}"
    mode: u=rwx,g=,o=

- name: Configure CLI
  template:
    src: cli.sh.j2
    dest: "{{ _rundeck_cli_user.home }}/.rd/rd.conf"
    owner: "{{ rundeck_cli_user }}"
    group: "{{ rundeck_cli_user }}"
    mode: u=rw,g=,o=
  when: rundeck_install_cli

- name: Configure LDAP
  template:
    src: jaas-ldap.conf.j2
    dest: "{{ rundeck_config_dir }}/jaas-ldap.conf"
    owner: "{{ rundeck_cli_user }}"
    group: "{{ rundeck_cli_user }}"
    mode: u=rwx,g=,o=
  when: rundeck_enable_ldap

- name: Configure SSL
  include_tasks: ssl.yml
  when: rundeck_enable_ssl

- name: Configure trusted certs
  include_tasks: trust.yml
  when: rundeck_trust_certs|length or rundeck_enable_ssl
