---
- name: Make sure apt can use TLS
  apt:
    name: apt-transport-https
    state: present
  when: rundeck_install_apt_transport_https

- name: Install Rundeck apt key
  apt_key:
    url: "{{ rundeck_apt_key_url }}"
    state: present
  when: rundeck_install_apt_key

- name: Install Rundeck apt repository
  apt_repository:
    repo: "{{ rundeck_apt_repo }}"
    state: present
    filename: rundeck
  when: rundeck_install_apt_repo

- name: Pin Rundeck package version
  copy:
    dest: /etc/apt/preferences.d/rundeck
    content: |
      Package: rundeck
      Pin: version {{ rundeck_version }}
      Pin-Priority: 1002
  when: rundeck_pin_version

- name: Install Rundeck
  apt:
    name: "{{ item }}"
    state: present
  # Uses with_items instead of loop to get apt optimization.
  with_items: "{{ _rundeck_packages }}"
