---
- name: Install for Debian family
  tags:
    - rundeck-install
  include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: Download plugins
  tags:
    - rundeck-plugins
  get_url:
    dest: "{{ rundeck_base_dir }}/libext/{{ item.url | basename }}"
    url: "{{ item.url }}"
    checksum: "{{ item.checksum | d(omit) }}"
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_group }}"
    mode: u=rw,g=r,o=r
  loop: "{{ rundeck_plugins }}"
  notify: restart rundeck

- name: Configure CLI
  tags:
    - rundeck-cli
  include_tasks: cli.yml
  when: rundeck_cli_enable

- name: Configure Rundeck
  import_tasks: configure.yml

# Flush first so that if a restart is pending, we don't start and immediately
# restart upon initial install.
- name: Flush pending handlers
  meta: flush_handlers

- name: Enable Rundeck service
  tags:
    - rundeck-configure
  service:
    name: rundeckd
    state: started
    enabled: yes
