---
- name: Prepare
  hosts: all
  tasks:
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - openjdk-8-jre-headless
        - ssl-cert
